### ISSUE TITLE
Add snippet for `@dd` directive

### ISSUE THREAD

**Issue by BrayanCaro** [yaegassy/coc-blade#16]
I think that a snippet for `@dd` directive could be awesome suggested by `b:dd~` (similar to `b:dump~`)

**Comment by yaegassy** [comment]
Sorry I didn't notice this issue. For coc-blade's directive completions and snippets, we use snippet data from this repository.

- <https://github.com/onecentlin/laravel-blade-snippets-vscode/blob/master/snippets/snippets.json>

Create an additional PR for `@dd` in the snippet data in this repository, or add
your own snippet for `@dd` using `coc-snippets`, etc.

**Comment by yaegassy** [comment]
@BrayanCaro Thanks!
