### ISSUE TITLE
Format error on version >= 0.18.8

### ISSUE THREAD

**Issue by HBSpy** [yaegassy/coc-blade#36]
When use version >= 0.18.8, I got error when format the code.
0.18.7 is the last success version.
I don't know it is a coc-blade issue? or a blade-formatter issue?
THX

```log
########## blade-formatter

TypeError: Y is not a function
```

**Comment by yaegassy** [comment]
Hi, thanks for the issue report. It seems that what is published to npm is not working properly...


1. Uninstall `coc-blade` installed by CocInstall

   ```vim
   :CocUninstall coc-blade
   ```

2. Then try installing it with your plugin manager, etc. Below is an example of vim-plug.

   ```vim
   Plug 'yaegassy/coc-blade', {'do': 'yarn install --frozen-lockfile'}
   ```

**Comment by yaegassy** [comment]
I have downgraded the version of the dependent package `blade-formatter`. It appears that there was an ESM-related problem.

- https://github.com/yaegassy/coc-blade/commit/2e627d01481b0829755d0801df5140f13ff70936

Already published in npm, try it `:CocUpgrade coc-blade`
